# Generated by Django 3.0.8 on 2020-07-13 14:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(choices=[('food', 'FOOD'), ('house-services', 'HOSE_SERVICES'), ('transportation', 'TRANSPORTATION'), ('drinks-parties', 'DRINKS_PARTIES'), ('hobbies', 'HOBBIES'), ('sports', 'SPORTS'), ('clothing', 'CLOTHING'), ('FURNITURE', 'FURNITURE'), ('home-appliance', 'HOME_APPLIANCE')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_id', models.UUIDField(default=uuid.uuid4)),
                ('expense_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=19)),
                ('expense_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expenses.ExpenseType')),
            ],
        ),
    ]
