# Generated by Django 3.0.8 on 2020-07-13 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user_id'], name='expenses_ex_user_id_51d8ba_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user_id', 'expense_date'], name='expenses_ex_user_id_69fe96_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user_id', 'expense_id'], name='expenses_ex_user_id_0434ec_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user_id', 'expense_type'], name='expenses_ex_user_id_c0d5a3_idx'),
        ),
    ]
